export const paths = {
  adminlogin: "/admin-login",
  login: "/",
  userManagement: "/user-management",
  userInvoices: "/user-invoice",
  accounts: "/accounts",
  loginLogs: "/loginLogs",
  invoiceLogs: "/invoiceLogs",
  invoiceManagement: "/invoice-management",
  supplierManagement: "/supplier-management",
  supplierManagementSupplier: "/supplier-management/supplier/:id",
  supplierComparison: "/supplier-comparison",
  supplierComparisonSupplier: "/supplier-comparison/supplier/:id",
  productLaunchTracker: "/product-launch-tracker",
  productLaunchTrackerProduct: "/product-launch-tracker/product/:id",
  dailyOperationsNotes: "/daily-operations-notes",
  dailyOperationsNotesNewNote: "/daily-operation-notes/new-note",
  productManagement: "/products-management",
  productManagementProduct: "/products-management/product/:id",
};
